<a href="https://colab.research.google.com/github/Seblao/Projet-Air-BnB/blob/main/02_Numpy_Vs_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Vectorized operations

As you could see in the quest, one of the great strengths of Numpy are the vectorized operations. Numpy will not perform loops to do calculations, but rather perform operations in parallel.   
You can look at it this way:  
* Python --> loop --> serial (actions one after the other)
* Numpy --> vectorized operation --> in parallel (actions next to each other)

# Mission 1

Considering the object below, we want to calculate the sum for each row.  
That is, return the sum of `12 + 5`, then `8 + 32` etc...  
Find a way to return the sums of the 4 rows in a list, coding in Python. You must have 4 values in this list.

In [8]:
my_list = [
           [12,5],
           [8,32],
           [25,6],
           [7,14]
]

somme_ligne = [sum(ligne) for ligne in my_list]

somme_ligne


[17, 40, 31, 21]

Now do the same thing, but this time coding in `Numpy`.  
`index`: You must first convert `my_list` to ndarray.

In [20]:
import numpy as np

data_np = np.array(my_list)
somme_ligne = np.sum(data_np, axis=1)

somme_ligne


array([17, 40, 31, 21])

# Mission 2

Find a way to return the sums of the 2 columns in a list, by coding in Python. You must have 2 values in this list.

In [13]:
my_list = [
           [12,5],
           [8,32],
           [25,6],
           [7,14]
]

somme_colonne = [0] * len(my_list[0])

for row in my_list:
    for i in range(len(row)):
      somme_colonne[i] += row[i]

somme_colonne

[52, 57]

Now do the same thing, but coding this time in Numpy.  
This time you have to propose 2 different solutions, coding in Numpy each time.


In [10]:
data_np = np.array(my_list)
somme_colonne = np.sum(data_np, axis=0)

somme_colonne

array([52, 57])

# Mission 3

This time, you will have to return the sum of all the elements included in the object below, coding in `Python`.

In [15]:
my_list = [
           [12,5],
           [8,32],
           [25,6],
           [7,14]
]

total = 0
for sous_liste in my_list:
    for element in sous_liste:
        total += element

total

109

As you might expect, you'll have to do this by coding in Numpy.
You can propose only one solution. There is a very simple one, and a very effective one too.

In [21]:
data_np = np.array(my_list)
total = np.sum(data_np)

total

109

# Mission 4

Find a way to calculate the following statistical indicators using NumPy functions on the array bellow.
- mode
- median
- average
- the range (the difference between max and min)
- standard deviation
- variance
- the different quantiles



In [33]:
array = [5, 34, 74, 65, 98, 81, 34, 61, 9, 4, 27, 42, 42, 78, 34, 59, 56, 82, 55, 63]

mode = np.bincount(array).argmax()
mode

34

In [27]:
median = np.median(array)
median

55.5

In [28]:
mean = np.mean(array)
mean

50.15

In [29]:
range = np.ptp(array)
range

94

In [30]:
std_dev = np.std(array)
std_dev

26.031279261688233

In [31]:
variance = np.var(array)
variance

677.6274999999998

In [32]:
quartiles = np.percentile(array, [25, 50, 75])
quartiles

array([34.  , 55.5 , 67.25])