<a href="https://colab.research.google.com/github/Seblao/Projet-Air-BnB/blob/main/Copy_of_03_Numpy_Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Execute the cell below before starting the 1st mission.

In [ ]:
array_1 = np.array([10, 40, 45,  5, 66, 91, 43, 75, 40, 28, 55, 45, 31, 71, 67, 54, 54,
       35, 64, 27, 12, 93, 17, 91, 50, 57, 74, 61, 86, 20, 36, 35])

array_1
array_1.shape

(32,)

# Mission 1

Using Numpy, how many axes `array_1` has ?




In [ ]:
# Array 1 possède 1 seul axe car 1 seule dimension puisque présence que d'1 seule ligne ici.

array_1[10]

55

Still using Numpy, how many dimensions `array_1` has?

In [ ]:
# Array_1 ne possède qu'une dimension car ici nous n'avons qu'1 seule ligne de valeurs.

array_1[20]

12

Display the first element of `array_1`

In [ ]:
array_1[0]

10

# Mission 2

Modify, using a `numpy` method, the `array_1` object to be an object that has two axes, including 1 row and 32 columns.  
Save it under the variable `array_2`.

In [ ]:
array_1_reshape = array_1.reshape(1, 32)
array_2 = array_1_reshape

array_2
array_2.shape

(1, 32)

Now, modify `array_1` into an object that has 32 rows and only 1 column.  
Save it under the variable `array_3`.

In [ ]:
array_1_reshape = array_1.reshape(32, 1)
array_3 = array_1_reshape

array_3.shape

(32, 1)

Access the first element of `array_2`, then of `array_3`.  
What do you notice?  
Why ?

In [ ]:
array_2[0]

array([10, 40, 45,  5, 66, 91, 43, 75, 40, 28, 55, 45, 31, 71, 67, 54, 54,
       35, 64, 27, 12, 93, 17, 91, 50, 57, 74, 61, 86, 20, 36, 35])

In [ ]:
array_3[0]

array([10])

In [ ]:
# On remarque que l'on obtient pas la meme chose. C'est normal car dans array_2, on appelle la ligne entière avec ces 32 colonnes alors que dans array_3, il n'y a qu'une seule colonne. D'où le résultat différent.

# Mission 3

Access the value that is at index 3 of array `array_2`.  
Do it with Numpy way, then with Python way.

In [ ]:
array_2 = np.array([10, 40, 45,  5, 66, 91, 43, 75, 40, 28, 55, 45, 31, 71, 67, 54, 54,
       35, 64, 27, 12, 93, 17, 91, 50, 57, 74, 61, 86, 20, 36, 35])

index_3 = array_2[3]

index_3

5

In [ ]:
array_2 = np.array([10, 40, 45,  5, 66, 91, 43, 75, 40, 28, 55, 45, 31, 71, 67, 54, 54,
       35, 64, 27, 12, 93, 17, 91, 50, 57, 74, 61, 86, 20, 36, 35])

liste_array_2 = list(array_2)

index_3 = liste_array_2[3]

index_3

5

Access the value which is at index 3 of array `array_3` in Numpy.

In [ ]:
array_3

index_3 = array_3[3, 0]

index_3

5

In [ ]:
# En python natif :
array_3

liste_array_3 = array_3[:, 0].tolist()

index_3 = liste_array_3[3]

index_3

5

# Mission 4

Reshape `array_1` to be a 4-row, 8-column array,
rather than a 32-element vector.  
Save your array under the variable `array_4`.

In [ ]:
array_1 = np.array([10, 40, 45,  5, 66, 91, 43, 75, 40, 28, 55, 45, 31, 71, 67, 54, 54,
       35, 64, 27, 12, 93, 17, 91, 50, 57, 74, 61, 86, 20, 36, 35])

array_4 = array_1.reshape(4, 8)

array_4

array([[10, 40, 45,  5, 66, 91, 43, 75],
       [40, 28, 55, 45, 31, 71, 67, 54],
       [54, 35, 64, 27, 12, 93, 17, 91],
       [50, 57, 74, 61, 86, 20, 36, 35]])

Access for each row, the values ​​of the columns which have the index 1 to 2 included.

In [ ]:
colonne_1_2 = array_4[:, 1:3]

colonne_1_2

array([[40, 45],
       [28, 55],
       [35, 64],
       [57, 74]])

Access for rows at position 1 and 2 inclusive, the values ​​of all columns.

In [ ]:
array_4
ligne_1_2 = array_4[0:2, :]

ligne_1_2

array([[10, 40, 45,  5, 66, 91, 43, 75],
       [40, 28, 55, 45, 31, 71, 67, 54]])

Access for the rows which have the index 2 to 3 inclusive, to the values ​​of the columns which have the index 3 to 5 inclusive.

In [ ]:
array_4

array([[10, 40, 45,  5, 66, 91, 43, 75],
       [40, 28, 55, 45, 31, 71, 67, 54],
       [54, 35, 64, 27, 12, 93, 17, 91],
       [50, 57, 74, 61, 86, 20, 36, 35]])

In [ ]:
ligne_2_3 = array_4[1:3, 2:5]

ligne_2_3

array([[55, 45, 31],
       [64, 27, 12]])

Select the first column, as well as the columns whose index is a multiple of 2.

In [ ]:
selected_columns = array_4[:, [0, 2, 4, 6]]

selected_columns

array([[10, 45, 66, 43],
       [40, 55, 31, 67],
       [54, 64, 12, 17],
       [50, 74, 86, 36]])

Select columns whose index is odd.

In [ ]:
selected_columns = array_4[:, 1::2]

selected_columns

array([[40,  5, 91, 75],
       [28, 45, 71, 54],
       [35, 27, 93, 91],
       [57, 61, 20, 35]])

# Mission 5

Reshape your `array_1` vector into a 3-dimensional array.
Your 3-dimensional array should have 2 matrices, each of which has 4 rows and 4 columns.
Save your array under the variable `array_5`.

In [ ]:
array_5d = array_1.reshape(2, 4, 4)

array_5d

array([[[10, 40, 45,  5],
        [66, 91, 43, 75],
        [40, 28, 55, 45],
        [31, 71, 67, 54]],

       [[54, 35, 64, 27],
        [12, 93, 17, 91],
        [50, 57, 74, 61],
        [86, 20, 36, 35]]])

Use the .shape attribute to observe the number of axes for `array_5`.

In [ ]:
array_5d.shape

(2, 4, 4)

Select all values ​​from the first matrix.

In [ ]:
first_matrice = array_5d[0]

first_matrice

array([[10, 40, 45,  5],
       [66, 91, 43, 75],
       [40, 28, 55, 45],
       [31, 71, 67, 54]])

Access for both matrices,
to the values ​​corresponding to the rows at index 1 and to the columns that have positions 3 and 4.

In [ ]:
array_5d

array([[[10, 40, 45,  5],
        [66, 91, 43, 75],
        [40, 28, 55, 45],
        [31, 71, 67, 54]],

       [[54, 35, 64, 27],
        [12, 93, 17, 91],
        [50, 57, 74, 61],
        [86, 20, 36, 35]]])

In [ ]:
ligne_1 = array_5d[0:2, 1, 2:4]

ligne_1

array([[43, 75],
       [17, 91]])

Access row values ​​at positions 2 to 3,
columns at indexes 1 to 3 included for the second matrix only.

In [ ]:
array_5d

array([[[10, 40, 45,  5],
        [66, 91, 43, 75],
        [40, 28, 55, 45],
        [31, 71, 67, 54]],

       [[54, 35, 64, 27],
        [12, 93, 17, 91],
        [50, 57, 74, 61],
        [86, 20, 36, 35]]])

In [ ]:
second_matrice = array_5d[1, 2:4, 1:4]

second_matrice

array([[57, 74, 61],
       [20, 36, 35]])


Reshape `array_5` so that we have 8 rows and 4 columns.

In [ ]:
array_new_5d = array_5d.reshape(8, 4)

array_new_5d

array([[10, 40, 45,  5],
       [66, 91, 43, 75],
       [40, 28, 55, 45],
       [31, 71, 67, 54],
       [54, 35, 64, 27],
       [12, 93, 17, 91],
       [50, 57, 74, 61],
       [86, 20, 36, 35]])