<a href="https://colab.research.google.com/github/Seblao/Projet-Air-BnB/blob/main/Copy_of_01_Numpy_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy : Introduction

**NumPy allows you to manipulate data in the form of an array.**

**Complete the missions below using NumPy.**

In [ ]:
import numpy as np # Here we rename numpy as np, it's shorter, and everybody does that

# Mission 1 : Display the version of NumPy you are running (as each library, you can use np.__version__)

np.__version__

'1.26.4'

In [ ]:
# Mission 2 : Create a NumPy array with a length of 3, that contains this 3 floats: 0.8, 0.6, 0.4
# Expected result: array([0.8, 0.6, 0.4])
data_list = [[0.8, 0.6, 0.4]]
data_np = np.array(data_list)

data_np[0, 0:3]

array([0.8, 0.6, 0.4])

In [ ]:
# Mission 3 : Create a function that uses the np.random.random() function to return an array with 10 random elements,
# all of which must be greater than 0.25 and less than 1.0

# Example of expected result: array([0.3897948 , 0.82850041, 0.5499838 , 0.81940137, 0.92175875, 0.89634373, 0.26821861, 0.72376496, 0.81098623, 0.28192741])

def generate_random_array():
    random_array = np.random.random(10)

    random_array = random_array * (1.0 - 0.25) + 0.25

    return random_array

array = generate_random_array()
array

array([0.99509177, 0.62505808, 0.62230031, 0.7199305 , 0.64416089,
       0.90103602, 0.59324984, 0.52817581, 0.87541662, 0.60239254])

In [ ]:
# Mission 4 : What does the np.empty() method do? Don't just copy the documentation, explain in your own words here

# La fonction np.empty() permet de créer 1 tableau dont on specifie les dimenssions de ce dernier (lignes et colonnes) mais dont les valeurs à l'intérieur du tableau seront déterminer aléatoirement.
# On ne donne pas de valeurs spécifiques.

In [ ]:
# Mission 5 : Create an array filled with only zeros. You can choose the length of this array.
taille = 10
tableau_zero = np.zeros(taille)
tableau_zero

# où :

matrice = np.zeros((10,5))
matrice

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# Mission 6 : Create an array filled with 10 random integers.
tableau_entiers = np.random.randint(0, 100, size=10)
tableau_entiers

array([67, 94, 21, 36, 21, 45, 70, 29, 95, 59])

In [ ]:
# Mission 7 : Create an array that contains 50 values randomly selected only from these numbers: 0, 1, 2, 3, 4, 5, 6, 7.
tableau_aleatoire = np.random.choice([0, 1, 2, 3, 4, 5, 6, 7], size=50)
tableau_aleatoire


array([5, 2, 3, 5, 2, 4, 3, 6, 6, 3, 4, 5, 0, 7, 3, 7, 0, 7, 3, 5, 4, 3,
       3, 3, 0, 7, 1, 1, 3, 2, 0, 5, 0, 2, 7, 1, 5, 6, 5, 1, 3, 3, 1, 0,
       1, 7, 0, 1, 4, 2])